# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programming blog of Johan Engelen
email: jbc.engelen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming blog of Johan Engelen. D, C++, LLVM, LDC, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johanengelen.github.io" # the base hostname & protocol for your site
github_username:  JohanEngelen

# Build settings
markdown: kramdown
kramdown:
  input: GFM

